server:
  port: ${SPRING_PORT}
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      auth: true
      starttls:
        enable: true
  profiles:
    include: oauth

verification:
  max_failed_attempts: ${MAX_FAILED_ATTEMPTS}
  default_expiry: ${DEFAULT_EXPIRY}
  max_chat_length : ${MAX_CHAT_LENGTH}

ai:
  url: ${AI_URL}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


cors:
  allowed-domains: ${CORS_ALLOWED_DOMAINS}