name : Deploy Action on Main Branch Merge

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name : Deploy To Server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/4th-1st-Project-3rd-BE
            
            git pull origin main
            
            ./gradlew clean build -x test
            
            sudo docker stop persona-chat-server
            
            sudo docker rm persona-chat-server
            
            sudo docker-compose --env-file .env.dev up -d --build